name: SDEX Group CI

on:
  push:
    branches: [ master ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .[docs]

      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: ./docs/source

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages